source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'UIKitten Catalog' do
  pod 'UIKitten', path: '../'
  pod 'UIKitten/Charts', path: '../'  
  pod 'UIKitten/Fontawesome', path: '../'    
end
